# Generated by Django 3.2.18 on 2023-03-25 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recordweight_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordweight',
            name='item',
        ),
        migrations.AddField(
            model_name='recordweight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 23, 1, 24, 72683)),
        ),
    ]
