# Generated by Django 3.2.18 on 2023-02-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.stock'),
        ),
    ]
