import Head from 'next/head'
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import styles from '@/styles/Home.module.css';
import Link from '@mui/material/Link';
import React from 'react';
import { useRouter } from 'next/router';
import Navbar from '@/components/Navbar';
import CardMedia from '@mui/material/CardMedia';
import { CardActionArea } from '@mui/material';


export default function Home() {
  const router = useRouter();
  React.useEffect(() => {
    if (!localStorage.getItem('token')) {
      router.push('/login');
    }
  }, []);

  const generateCards = () => {
    const elements = [
      {
        imgUrl: "https://opabargroup.s3.amazonaws.com/images/sector.png",
        label: "Sectores",
        alt: "sectores",
        href: "/sectores"
      },
      {
        imgUrl: "https://opabargroup.s3.amazonaws.com/images/registro.png",
        label: "Registrar pesos",
        alt: "registrar pesos",
        href: "/registrar-pesos"
      },
      {
        imgUrl: "https://opabargroup.s3.amazonaws.com/images/mis_registros.png",
        label: "Mis Registros",
        alt: "mis registros",
        href: "/registros"
      },
      {
        imgUrl: "https://opabargroup.s3.amazonaws.com/images/dashboard.jpg",
        label: "Dashboard",
        alt: "dashboard",
        href: "/dashboard"
      }
    ]
    const cards = elements.map( ele => {
      return <Grid item xs={12} sm={6} md={4} key={ele.href}>
                <Card sx={{ minWidth: 200, maxWidth: 250 }}>
                <Link color="inherit" href={ele.href}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image={ele.imgUrl}
                      alt={ele.alt}
                    />
                    <CardContent>
                      <Typography variant="h5" component="div">
                        {ele.label}
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </Link>
                </Card>
              </Grid>
    });
    return (
      <>
        {cards}
      </>
    )
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <Box sx={{ width: '100%' }}>
          <Grid container rowSpacing={2} columnSpacing={{ xs: 1, sm: 8, md: 10 }}>
            {generateCards()}
          </Grid>
        </Box>
      </main>
    </>
  )
}
