import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import styles from '@/styles/Home.module.css';
import Link from '@mui/material/Link';
import React from 'react';
import { useRouter } from 'next/router';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  React.useEffect(() => {
    if (!localStorage.getItem('token')) {
      router.push('/signIn');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        
      <Box sx={{ width: '100%' }}>
        <Grid container rowSpacing={2} columnSpacing={{ xs: 1, sm: 8, md: 10 }}>
          <Grid item xs={12} sm={4} md={3}>
            <Card sx={{ minWidth: 200, maxWidth: 250 }}>
              <CardContent>
                {/* <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom>
                  Word of the Day
                </Typography> */}
                <Typography variant="h5" component="div">
                  Sectores
                </Typography>
                {/* <Typography sx={{ mb: 1.5 }} color="text.secondary">
                  adjective
                </Typography>
                <Typography variant="body2">
                  well meaning and kindly.
                  <br />
                  {'"a benevolent smile"'}
                </Typography> */}
              </CardContent>
              <CardActions>
                <Button size="small"><Link color="inherit" href="/sectores">Ver</Link></Button>
              </CardActions>
            </Card>
          </Grid>
          <Grid item xs={12} sm={4} md={3}>
            <Card sx={{ minWidth: 200, maxWidth: 250 }}>
              <CardContent>
                <Typography variant="h5" component="div">
                  Registro de pesos
                </Typography>
              </CardContent>
              <CardActions>
                <Button size="small"><Link color="inherit" href="/registrar-pesos">Ver</Link></Button>
              </CardActions>
            </Card>
          </Grid>
        </Grid>
      </Box>
          

          
        
      </main>
    </>
  )
}
